[helpers]

[default]
depends = []

[default.files]
".gitconfig" = "~/.gitconfig"

[default.variables]
git = { name = "Konnor Klercke", email = "klercke@protonmail.com", signingkey = "249DF839A80D37DD" }

[nvim]
depends = []

[nvim.variables]
editor = "nvim"

[nvim.files]
nvim = "~/.config/nvim/"

[settings]
default_target_type = "automatic"
