[helpers]

[default]
depends = []

[default.files]
".gitconfig" = "~/.gitconfig"

[default.variables]

[nvim]
depends = []

[nvim.variables]
editor = "nvim"

[nvim.files]
nvim = "~/.config/nvim/"

[settings]
default_target_type = "automatic"
